export const STATUS = { new: '新規', ai_handling: 'LINE受付中', human_review: '確認待ち', tour: '見学', interview: '面接', hold: '保留・契約待ち', hired: '採用', rejected: '見送り', withdrawn: '辞退' } as const;
export type Status = keyof typeof STATUS;
export type StaffDepartment = 'admin' | 'therapy' | 'welfare';
export type Applicant = { id: string; display_name: string | null; department: 'therapy' | 'welfare' | 'unknown'; desired_job: string | null; qualifications: string | null; desired_schedule: string | null; desired_start: string | null; can_drive: string | null; status: Status; source: string; ai_summary: string | null; intake_state?: { answers?: Record<string,string>; entry?: string; mode?: string }; created_at: string; updated_at: string; phone?: string; age_text?: string; contact_date?: string; appointment_date?: string; appointment_kind?: string; admin_note?: string; result_reason?: string; legacy_key?: string; staff_reply_mode?: boolean; recruitment_media?:string;archived_at?:string|null };
export type Message = { id: string; direction: 'inbound' | 'outbound' | 'internal'; body: string; created_at: string; channel?: string; staff_name?: string | null };
export type Job = { id: string; department: string; title: string; employment_type: string | null; salary_text: string | null; schedule_text: string | null; location_text: string | null; description: string | null; active: boolean };
export function localDate(d = new Date()) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
export function dateLabel(value?: string | null) { if (!value) return '未設定'; if (/^\d{4}-\d{2}-\d{2}$/.test(value)) { const [y,m,d] = value.split('-').map(Number); return new Date(y,m-1,d).toLocaleDateString('ja-JP'); } return new Date(value).toLocaleString('ja-JP'); }
export function canAccess(role: StaffDepartment, department: string) { return role === 'admin' || role === department; }
export function latestAnswers(row: Applicant) { const a = row.intake_state?.answers ?? {}; const labels: Record<string,string> = {work:'仕事',role:'職種',employment:'雇用形態',sideJob:'副業',time:'勤務条件',frequency:'勤務回数',qualification:'資格',drive:'運転',start:'開始希望',next:'次の希望',visitTiming:'見学希望時間帯',consultTopic:'相談項目',consultNote:'相談内容',contactMethod:'希望連絡方法',contactPhone:'連絡先電話番号',contactEmail:'連絡先メールアドレス',contactDeferred:'連絡先の確認'}; return Object.entries(labels).filter(([k])=>typeof a[k]==='string' && a[k]).map(([k,label])=>({label,value:a[k]})); }
export function filteredApplicants(rows: Applicant[], q: string, department: string, status: string) { const query=q.trim().toLocaleLowerCase(); return rows.filter(r=>(!department || r.department===department) && (!status || r.status===status) && (!query || [r.display_name,r.desired_job,r.desired_schedule,r.phone,r.recruitment_media,r.admin_note,...latestAnswers(r).map(a=>a.value)].join(' ').toLocaleLowerCase().includes(query))).slice().sort((a,b)=>b.updated_at.localeCompare(a.updated_at)); }
export function parseCSV(input: string): string[][] { const text=input.replace(/^\uFEFF/,''); const rows:string[][]=[];let row:string[]=[],cell='',quoted=false; for(let i=0;i<text.length;i++){const c=text[i]; if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell){throw new Error('CSVの引用符を確認してください。');}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;} if(quoted)throw new Error('CSVの引用符が閉じていません。');row.push(cell);if(row.some(Boolean))rows.push(row);return rows; }
export type LegacyRecord = { display_name: string; department: 'welfare'; desired_job: string; qualifications: string; desired_schedule: string; source: 'legacy'; status: Status; phone: string; age_text: string; contact_date: string; appointment_date: string; appointment_kind: string; admin_note: string; result_reason: string; legacy_key?: string; staff_reply_mode?: boolean; recruitment_media?:string };
function checkedDate(value: string, line: number) { if(!value)return ''; if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(`${line}行目の日付はYYYY-MM-DDで入力してください。`);const [y,m,d]=value.split('-').map(Number); if(localDate(new Date(y,m-1,d))!==value)throw new Error(`${line}行目の日付が正しくありません。`);return value; }
export function importLegacyCSV(text: string): LegacyRecord[] { const [head,...rows]=parseCSV(text); if(!head?.includes('氏名')||!head.includes('選考状況'))throw new Error('旧採用アプリの「応募者一覧」から出力したCSVを選んでください。');if(rows.length>500)throw new Error('一度に取り込めるのは500件です。'); const stages:Record<string,Status>={'新規・未対応':'new','新規':'new','応募':'new','選考中':'human_review','選考':'human_review','見学・面接':'interview','面接':'interview','見学':'tour','採用':'hired','見送り':'rejected','辞退':'withdrawn','保留':'hold','契約待ち':'hold'};return rows.map((values,index)=>{const get=(key:string)=>values[head.indexOf(key)]?.trim()??'';const line=index+2;if(values.length!==head.length)throw new Error(`${line}行目の列数が違います。`);const name=get('氏名');if(!name||name.length>200)throw new Error(`${line}行目の氏名を確認してください。`);const originalStage=get('選考状況'),status=stages[originalStage];if(!status)throw new Error(`${line}行目の選考状況「${originalStage}」は未対応です。`);return {display_name:name,department:'welfare',desired_job:get('希望職種'),qualifications:get('保有資格'),desired_schedule:get('シフト/頻度'),source:'legacy',recruitment_media:get('応募媒体')||'不明',status:get('見送り理由')==='辞退'?'withdrawn':status,phone:get('電話番号'),age_text:get('年齢'),contact_date:checkedDate(get('連絡日'),line),appointment_date:checkedDate(get('見学・面接日'),line),appointment_kind:'面接・見学',result_reason:get('見送り理由'),admin_note:[get('進行メモ'),`旧媒体：${get('応募媒体')||'未設定'} / 旧選考状況：${originalStage}`].filter(Boolean).join('\n')};}); }
export async function legacyKey(row: LegacyRecord) { const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(Object.fromEntries(Object.entries(row).filter(([key])=>key!=='recruitment_media')))));return 'planet-v1:'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join(''); }
export function exportApplicantsCSV(rows: Applicant[]) { const cell=(v:unknown)=>{const s=String(v??'');return `"${(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replace(/"/g,'""')}"`;}; const header=['ID','氏名','部門','登録経路','応募媒体','希望職種','シフト/頻度','保有資格','電話番号','希望連絡方法','連絡先メールアドレス','連絡先の確認','年齢','連絡日','見学・面接日','選考状況','見送り理由','進行メモ'];return '\uFEFF'+[header,...rows.map(r=>[r.id,r.display_name,r.department==='therapy'?'療術':r.department==='welfare'?'福祉':'未選択',r.source,r.recruitment_media||(/旧媒体：([^\n]+?) \/ 旧選考状況：/.exec(r.admin_note??'')?.[1])||(r.source==='line'?'LINE':'不明'),r.desired_job,r.desired_schedule,r.qualifications,r.phone||r.intake_state?.answers?.contactPhone,r.intake_state?.answers?.contactMethod,r.intake_state?.answers?.contactEmail,r.intake_state?.answers?.contactDeferred,r.age_text,r.contact_date,r.appointment_date,STATUS[r.status],r.result_reason,r.admin_note])].map(r=>r.map(cell).join(',')).join('\r\n'); }
export function demoApplicants(): Applicant[] { const now=new Date().toISOString();const base={qualifications:null,desired_schedule:null,desired_start:null,can_drive:null,ai_summary:null,created_at:now,updated_at:now}; return [ {...base,id:'demo-clinic',display_name:'サンプル・院応募者',department:'therapy',desired_job:'受付',status:'human_review',source:'line',intake_state:{answers:{work:'院での施術・受付',role:'受付',employment:'パートを希望',frequency:'週2〜3回',consultTopic:'勤務条件を相談',consultNote:'午前中心で働けるか相談したいです。',contactMethod:'電話',contactPhone:'09000000000'}}}, {...base,id:'demo-home',display_name:'サンプル・GH応募者',department:'welfare',desired_job:'生活支援・夜間見守り',status:'human_review',source:'line',intake_state:{answers:{work:'グループホーム',role:'生活支援・夜間見守り',time:'22〜翌5時',frequency:'週1回程度',next:'まず見学したい',visitTiming:'平日の夕方',contactMethod:'メール',contactEmail:'sample@example.com'}}}, {...base,id:'demo-legacy',recruitment_media:'engage',display_name:'サンプル・旧アプリ応募者',department:'welfare',desired_job:'夜勤専従',desired_schedule:'週2回',status:'interview',source:'legacy',appointment_date:localDate(),appointment_kind:'面接',admin_note:'旧採用管理から統合した例です。'}, {...base,id:'demo-visit',display_name:'サンプル・訪問応募者',department:'therapy',desired_job:'訪問マッサージ',status:'ai_handling',source:'line'}, {...base,id:'demo-hired',recruitment_media:'紹介',display_name:'サンプル・採用決定',department:'welfare',desired_job:'世話人',status:'hired',source:'manual'} ]; }
export function importLegacyJSON(text:string):LegacyRecord[]{
 let data:unknown;try{data=JSON.parse(text);}catch{throw new Error('JSONの形式を確認してください。');}
 if(!Array.isArray(data)||data.length>500)throw new Error('旧採用アプリの応募者配列（500件まで）を選んでください。');
 const stages:Record<string,string>={new:'新規',screening:'選考中',interview:'見学・面接',hired:'採用',closed:'見送り',hold:'契約待ち',withdrawn:'辞退'};
 const head=['氏名','年齢','電話番号','応募媒体','希望職種','シフト/頻度','保有資格','連絡日','見学・面接日','選考状況','見送り理由','進行メモ'];
 const lines=data.map((value,index)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${index+1}件目の応募者を確認してください。`);const row=value as Record<string,unknown>;if(typeof row.name!=='string'||typeof row.stage!=='string'||!stages[row.stage])throw new Error(`${index+1}件目の氏名・選考状況を確認してください。`);const keys=['name','age','phone','media','job','freq','qual','contact','interview','stage','result','note'];return keys.map(key=>{const v=key==='stage'?stages[String(row.stage)]:row[key];if(v!=null&&typeof v!=='string'&&typeof v!=='number')throw new Error(`${index+1}件目の項目「${key}」を確認してください。`);return String(v??'');});});
 const cell=(value:string)=>`"${value.replace(/"/g,'""')}"`;
 return importLegacyCSV([head,...lines].map(row=>row.map(cell).join(',')).join('\r\n'));
}
