'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {Applicant,Message} from '@/lib/recruiting-admin';
import {CONTACT_ASK,CONTACT_CHOICES} from '@/lib/recruiting-contact';
import {dateLabel} from '@/lib/recruiting-admin';
type Attempt={id:string;body:string;state:'sending'|'accepted'|'failed'|'unknown';staff_name:string;error_code:string|null;created_at:string;updated_at:string};
type Intent={id:string;text:string};
const codes:Record<string,string>={QUOTA_EXHAUSTED:'LINEの月間配信枠に達したため送信しませんでした。',QUOTA_UNVERIFIED:'LINEの配信枠を確認できません。管理者に配信プランの確認を依頼してください。',CHANNEL_MISMATCH:'接続先のLINEアカウントが一致しないため停止しました。',LINE_NOT_CONFIGURED:'LINE接続の設定が必要です。',LINE_LIMIT:'LINEの配信数または通信回数の上限に達しました。',PREFLIGHT_FAILED:'LINE接続・配信枠を確認できなかったため送信しませんでした。'};
export default function LineReplyComposer({applicant,demo,client,onBusy,onUpdated}:{applicant:Applicant;demo:boolean;client:SupabaseClient|null;onBusy:(busy:boolean)=>void;onUpdated:(message?:Message)=>Promise<void>}){
 const [template,setTemplate]=useState('custom');
 const [text,setText]=useState(''),[confirm,setConfirm]=useState(false),[intent,setIntent]=useState<Intent|null>(null),[sending,setSending]=useState(false),[info,setInfo]=useState(''),[error,setError]=useState(''),[attempts,setAttempts]=useState<Attempt[]>([]),[loading,setLoading]=useState(false),[recordError,setRecordError]=useState(false),[cooldown,setCooldown]=useState(0),[expired,setExpired]=useState(false),[resumeConfirm,setResumeConfirm]=useState(false);
 const sendingRef=useRef(false),active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 useEffect(()=>{if(!cooldown)return;const t=setTimeout(()=>setCooldown(cooldown-1),1000);return()=>clearTimeout(t);},[cooldown]);
 const refresh=useCallback(async()=>{if(demo||!client)return;setLoading(true);try{const {data,error:e}=await client.from('recruiting_outbox').select('id,body,state,staff_name,error_code,created_at,updated_at').eq('applicant_id',applicant.id).order('created_at',{ascending:false}).limit(20);if(!active.current)return;if(e){setRecordError(true);return;}setRecordError(false);const list=(data??[]) as Attempt[];setAttempts(list);const pending=list.find(a=>a.state==='sending'||a.state==='unknown');if(pending){setIntent({id:pending.id,text:pending.body});setText(pending.body);setExpired(Date.now()-new Date(pending.created_at).getTime()>=23*60*60*1000);}else setExpired(false);}catch{if(active.current)setRecordError(true);}finally{if(active.current)setLoading(false);}},[applicant.id,client,demo]);
 useEffect(()=>{void refresh();},[refresh]);
 const pending=attempts.find(a=>a.state==='sending'||a.state==='unknown');
 const locked=Boolean(intent)||Boolean(pending);
 const visibleText=intent?.text??text;
 function compose(value:string){if(locked||sending)return;setText(value);setConfirm(false);setError('');setInfo('');}
 function showConfirmation(){if(!visibleText.trim()||visibleText.length>5000||sending||recordError||expired)return;setConfirm(true);setError('');setInfo('');}
 async function send(){if(sendingRef.current||!confirm||expired)return;sendingRef.current=true;setSending(true);onBusy(true);setError('');setInfo('');const current=intent??{id:crypto.randomUUID(),text};setIntent(current);try{
 if(demo){const message:Message={id:current.id,direction:'outbound',channel:'line_staff',body:current.text,staff_name:'デモ管理者',created_at:new Date().toISOString()};await onUpdated(message);if(active.current){setInfo('デモの送信履歴へ追加しました。実際のLINEへは送信していません。');setText('');setTemplate('custom');setIntent(null);setConfirm(false);}return;}
 if(!client)throw new Error('AUTH_REQUIRED');const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('AUTH_REQUIRED');
 const response=await fetch('/api/line/staff-reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({requestId:current.id,applicantId:applicant.id,text:current.text}),signal:AbortSignal.timeout(35000)});
 const result=await response.json();if(!response.ok){if(['AUTH_REQUIRED','FORBIDDEN','INVALID_BODY','LINE_NOT_LINKED'].includes(result.error)){setIntent(null);setConfirm(false);throw new Error(result.error);}throw new Error('RESULT_UNKNOWN');}
 if(!active.current)return;
 if(result.status==='accepted'){setInfo('LINEが送信を受け付けました。相手への到達・既読は確認できません。');setText('');setTemplate('custom');setIntent(null);setConfirm(false);await refresh();await onUpdated();}
 else if(result.status==='failed'){setError(codes[result.code]??'LINEへの送信は受け付けられませんでした。設定や入力内容を確認してください。');setIntent(null);setConfirm(false);await refresh();await onUpdated();}
 else if(result.status==='expired'){setExpired(true);setError('安全に再試行できる時間を過ぎています。重複送信を防ぐため、管理者による送信結果の確認が必要です。');setConfirm(false);}
 else{setCooldown(result.status==='in_progress'?15:10);setError(result.status==='pending_other'?'この応募者には確認中の送信があります。送信記録から内容を確認してください。':'送信結果を確認中です。文章を変えて送り直さず、同じ送信の再試行を使ってください。');setConfirm(false);await refresh();await onUpdated();}
 }catch(e){if(!active.current)return;const code=String((e as Error).message);setError(code==='AUTH_REQUIRED'?'ログインし直してください。':code==='FORBIDDEN'?'この応募者へ返信する権限がありません。':code==='LINE_NOT_LINKED'?'応募者のLINE接続がありません。':code==='INVALID_BODY'?'返信内容を確認してください。':'通信が途切れ、送信結果が未確認です。重複送信を防ぐため、同じ内容・同じ送信として再試行してください。');if(!['AUTH_REQUIRED','FORBIDDEN','INVALID_BODY','LINE_NOT_LINKED'].includes(code))setCooldown(10);setConfirm(false);await refresh();
 }finally{sendingRef.current=false;if(active.current)setSending(false);onBusy(false);}}
 async function resume(){if(sendingRef.current||!resumeConfirm)return;sendingRef.current=true;setSending(true);onBusy(true);setError('');try{if(demo){await onUpdated({id:crypto.randomUUID(),direction:'internal',channel:'admin',body:'自動受付を再開しました。',created_at:new Date().toISOString()});}else{const {error:e}=await client!.rpc('recruiting_resume_auto',{p_applicant_id:applicant.id,p_expected_updated_at:applicant.updated_at});if(e)throw e;await onUpdated();}setInfo('自動受付を再開しました。次に届くメッセージから受付を続けます。');setResumeConfirm(false);}catch{setError('自動受付を再開できませんでした。一覧を更新し、選考状況と確認中の送信を確認してください。');}finally{sendingRef.current=false;if(active.current)setSending(false);onBusy(false);}}
 if(applicant.source!=='line')return <div className="section"><h3>LINEへの返信</h3><p className="muted">この応募者はLINEからの応募ではありません。LINE連携のある応募者へ返信できます。</p></div>;
 return <div className="section reply-composer"><h3>LINEへ返信する</h3><p className="muted">送信先：<strong>{applicant.display_name||'LINE応募者（氏名未取得）'}</strong>。担当者返信を始めると、この応募者への自動返信を停止します。</p>{applicant.staff_reply_mode&&<div className="banner">担当者対応中：自動返信を停止しています。{!pending&&['new','ai_handling','human_review'].includes(applicant.status)&&<><button type="button" disabled={sending||locked} onClick={()=>setResumeConfirm(true)}>自動受付を再開する</button>{resumeConfirm&&<div><p>この応募者の自動受付を再開しますか？</p><div className="actions"><button type="button" disabled={sending} onClick={()=>setResumeConfirm(false)}>キャンセル</button><button type="button" disabled={sending} onClick={()=>void resume()}>再開する</button></div></div>}</>}</div>}{loading&&<p role="status">送信記録を確認しています…</p>}{recordError&&<div className="banner error" role="alert">送信記録を確認できません。管理機能のDB設定や接続を確認してください。<button type="button" onClick={()=>void refresh()} disabled={sending}>送信記録を更新する</button></div>}
 <label>返信の種類<select aria-label="返信の種類" value={template} disabled={locked||sending} onChange={e=>{setTemplate(e.target.value);compose(e.target.value==='contact'?CONTACT_ASK:e.target.value==='visit'?'見学をご希望いただき、ありがとうございます。\n担当者から日程の候補をご案内します。気になることも、気軽にご相談ください。':e.target.value==='consult'?'こんにちは。イトーメディカルケアの採用担当です。\nご相談ありがとうございます。担当者が内容を確認しました。これからご希望に合わせてご案内します。':'');}}><option value="custom">自由に返信する</option><option value="contact">希望の連絡方法を聞く（電話・メール・LINE）</option><option value="consult">相談へのお返事</option><option value="visit">見学のご案内</option></select></label>{visibleText===CONTACT_ASK&&<div className="section"><p>応募者には次の3つの選択肢が表示されます。</p><div className="actions">{CONTACT_CHOICES.map(c=><span className="badge" key={c.text}>{c.label}</span>)}</div><p className="muted">電話・メールの希望を選んだ後は、連絡先を自動受付で確認します。</p></div>}<label>返信内容<textarea aria-label="LINEの返信内容" maxLength={5000} value={visibleText} disabled={sending||locked||template==='contact'} onChange={e=>compose(e.target.value)} placeholder="応募者に伝えたい内容を入力してください。"/></label><p className="muted">{visibleText.length} / 5,000文字。この担当者返信はLINEの月間配信数にカウントされます。</p>{info&&<p className="banner" role="status">{info}</p>}{error&&<p className="banner error" role="alert">{error}</p>}
 {confirm?<div className="send-confirm"><h3>送信内容の確認</h3><p>送信先：<strong>{applicant.display_name||'LINE応募者（氏名未取得）'}</strong></p><div className="message-preview">{visibleText}</div>{visibleText===CONTACT_ASK&&<p>選択肢：電話 → メール → LINE</p>}<p className="muted">{demo?'デモ履歴だけに追加します。':'この文面を応募者のLINEへ送信します。送信後の取消しはできません。'}</p><div className="actions"><button type="button" disabled={sending} onClick={()=>setConfirm(false)}>戻る</button><button type="button" className="primary" disabled={sending||cooldown>0||expired} onClick={()=>void send()}>{sending?'送信しています…':demo?'デモで送信を確認する':'この内容をLINEへ送信する'}</button></div></div>:<button type="button" className="primary" disabled={sending||loading||recordError||!visibleText.trim()||visibleText.length>5000||cooldown>0||expired} onClick={showConfirmation}>{cooldown>0?`${cooldown}秒後に再確認できます`:locked?'同じ送信の再試行を確認する':'送信内容を確認する'}</button>}
 {attempts.length>0&&<div className="section"><h3>最近の送信記録</h3>{attempts.slice(0,5).map(a=><div className="attempt" key={a.id}><strong>{a.state==='accepted'?'LINE受付済み':a.state==='failed'?'送信未受付':'結果確認中'}</strong><span className="muted"> / {a.staff_name} / {dateLabel(a.created_at)}</span><p>{a.body}</p></div>)}<button type="button" onClick={()=>void refresh()} disabled={sending||loading}>送信記録を更新する</button></div>}
 </div>;
}
