'use client';
import {useState} from 'react';
import {localDate,dateLabel,STATUS,type Applicant} from '@/lib/recruiting-admin';
import {calendarDays,shiftPeriod,parseDay,eventsForDay,type CalendarField} from '@/lib/recruiting-calendar';
export default function RecruitingCalendar({rows,onOpen,onCreate,onMove,busy}:{rows:Applicant[];onOpen:(r:Applicant)=>void;onCreate:(date:string,field:CalendarField)=>void;onMove:(r:Applicant,date:string,field:CalendarField)=>Promise<boolean>;busy:boolean}){
 const [current,setCurrent]=useState(localDate()),[selected,setSelected]=useState(localDate()),[mode,setMode]=useState<'month'|'week'>('month'),[field,setField]=useState<CalendarField|'both'>('appointment_date'),[dragging,setDragging]=useState(''),[over,setOver]=useState(''),[pending,setPending]=useState<{id:string;date:string;field:CalendarField}|null>(null),[moveField,setMoveField]=useState<CalendarField>('appointment_date'),[moveId,setMoveId]=useState(''),[moveDate,setMoveDate]=useState(localDate());
 const days=calendarDays(current,mode),day=parseDay(current),today=localDate(),selectedRows=eventsForDay(rows,selected,field),movingRow=rows.find(r=>r.id===pending?.id),dateRows=rows.filter(r=>r[moveField]);
 function step(n:number){const next=shiftPeriod(current,mode,n);setCurrent(next);setSelected(next);setPending(null);}
 function propose(id:string,date:string,kind:CalendarField=moveField){const row=rows.find(r=>r.id===id);if(!busy&&row&&row[kind]!==date)setPending({id,date,field:kind});setDragging('');setOver('');}
 return <section className="panel calendar-panel"><div className="calendar-toolbar"><div className="actions"><button disabled={busy} aria-label="前の期間" onClick={()=>step(-1)}>前へ</button><button disabled={busy} onClick={()=>{setCurrent(today);setSelected(today);}}>今日</button><button disabled={busy} aria-label="次の期間" onClick={()=>step(1)}>次へ</button></div><h2>{mode==='month'?`${day.getFullYear()}年${day.getMonth()+1}月`:`${dateLabel(days[0])}〜${dateLabel(days[6])}`}</h2><div className="actions"><button aria-pressed={mode==='month'} className={mode==='month'?'primary':''} disabled={busy} onClick={()=>{setMode('month');setPending(null);}}>月表示</button><button aria-pressed={mode==='week'} className={mode==='week'?'primary':''} disabled={busy} onClick={()=>{setMode('week');setPending(null);}}>週表示</button><label>表示する日付<select value={field} disabled={busy} onChange={e=>{setField(e.target.value as CalendarField|'both');setPending(null);}}><option value="appointment_date">見学・面接予定</option><option value="contact_date">連絡日</option><option value="both">両方を表示</option></select></label></div></div>
 <p className="muted">表示期間の登録 {days.filter(key=>mode==='week'||parseDay(key).getMonth()===day.getMonth()).reduce((n,key)=>n+eventsForDay(rows,key,field).length,0)}件</p><p className="muted">日付を選ぶと下に詳細を表示します。PCでは予定を別の日へドラッグできます。スマホは下の「日程を変更する」を使えます。</p>
 <div className="calendar-weekdays" aria-hidden="true">{['日','月','火','水','木','金','土'].map(w=><span key={w}>{w}</span>)}</div><div className={`calendar-grid ${mode}`}>{days.map(key=>{const events=eventsForDay(rows,key,field);return <div key={key} data-date={key} className={`calendar-cell ${parseDay(key).getMonth()!==day.getMonth()&&mode==='month'?'outside':''} ${over===key?'drop-over':''} ${selected===key?'chosen':''}`} onDragOver={e=>{if(!busy&&dragging){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(key);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver('');}} onDrop={e=>{e.preventDefault();if(!busy){try{const data=JSON.parse(e.dataTransfer.getData('application/x-ito-calendar'));if(['appointment_date','contact_date'].includes(data.kind))propose(data.id,key,data.kind);}catch{setDragging('');setOver('');}}}}><button className={`calendar-day ${key===today?'today':''}`} disabled={busy} aria-label={`${dateLabel(key)}、${events.length}件`} aria-pressed={selected===key} onClick={()=>{setSelected(key);setMoveDate(key);}}>{parseDay(key).getDate()}<span className="calendar-count">{events.length?`${events.length}件`:''}</span></button><div className="calendar-events">{events.slice(0,3).map(({row:r,kind})=><button key={r.id+kind} data-event={r.id} draggable={!busy} disabled={busy} className={`calendar-event ${r.department==='therapy'?'therapy':'welfare'} ${dragging===r.id?'dragging':''}`} onDragStart={e=>{e.dataTransfer.setData('application/x-ito-calendar',JSON.stringify({id:r.id,kind}));e.dataTransfer.effectAllowed='move';setDragging(r.id);}} onDragEnd={()=>{setDragging('');setOver('');}} onClick={()=>onOpen(r)}><strong>{r.display_name||'氏名未取得'}</strong><small>{kind==='appointment_date'?r.appointment_kind||'予定':'連絡'} / {STATUS[r.status]}</small></button>)}{events.length>3&&<button className="calendar-more" onClick={()=>setSelected(key)}>ほか{events.length-3}件</button>}</div></div>;})}</div>
 <section className="section"><div className="heading"><h3>{dateLabel(selected)}の{field==='contact_date'?'連絡':'予定'}</h3><button disabled={busy} onClick={()=>onCreate(selected,field==='both'?'appointment_date':field)}>この日に応募者を追加する</button></div>{selectedRows.length?<div className="row-list">{selectedRows.map(({row:r,kind})=><button className="applicant-row" key={r.id+kind} disabled={busy} onClick={()=>onOpen(r)}><span className="row-main"><strong>{r.display_name||'氏名未取得'}</strong><span>{r.department==='therapy'?'療術部門':'GH部門'} / {kind==='appointment_date'?r.appointment_kind||'予定':'連絡'} / {STATUS[r.status]}</span></span></button>)}</div>:<p className="empty">この日の登録はありません。応募者詳細から日程を設定できます。</p>}</section>
 <form className="calendar-move" onSubmit={e=>{e.preventDefault();propose(moveId,moveDate);}}><h3>日程を変更する</h3><div className="form-grid"><label>変更する日付の種類<select value={moveField} disabled={busy} onChange={e=>{setMoveField(e.target.value as CalendarField);setMoveId('');}}><option value="appointment_date">見学・面接日</option><option value="contact_date">連絡日</option></select></label><label>変更する応募者<select required value={moveId} disabled={busy||!dateRows.length} onChange={e=>setMoveId(e.target.value)}><option value="">応募者を選ぶ</option>{dateRows.map(r=><option key={r.id} value={r.id}>{r.display_name||'氏名未取得'} / {dateLabel(r[moveField])}</option>)}</select></label><label>変更先の日付<input type="date" required value={moveDate} disabled={busy} onChange={e=>setMoveDate(e.target.value)}/></label></div><button disabled={busy||!moveId||!moveDate}>変更内容を確認する</button></form>
 {pending&&movingRow&&<div className="calendar-confirm" role="region" aria-label="日程変更の確認"><h3>日程変更の確認</h3><p>{movingRow.display_name||'氏名未取得'}の{pending.field==='appointment_date'?'見学・面接日':'連絡日'}を、{dateLabel(movingRow[pending.field])}から<strong>{dateLabel(pending.date)}</strong>へ変更します。</p><p className="muted">選考状況とメモはそのまま保存します。応募者への連絡は、保存後に担当者から行ってください。</p><div className="actions"><button disabled={busy} onClick={()=>setPending(null)}>変更を取り消す</button><button className="primary" disabled={busy} onClick={()=>{void onMove(movingRow,pending.date,pending.field).then(saved=>{if(saved){setSelected(pending.date);setCurrent(pending.date);setPending(null);}});}}>{busy?'保存しています…':'日程を保存する'}</button></div></div>}
 </section>;
}
