'use client';
import {useEffect,useRef,useState} from 'react';
import {mediaOf,jobOf} from '@/lib/recruiting-portal';
import {validateMaster,type Master,type Department} from '@/lib/recruiting-master';
import type {Applicant,StaffDepartment} from '@/lib/recruiting-admin';
export type Rename={kind:'media'|'job';oldName:string;newName:string};
export type Preferences={density:'comfortable'|'compact';startView:'dashboard'|'board'|'calendar'|'list'};
type Category='display'|'media'|'jobs'|'access';
export default function RecruitingSettings({masters,rows,onSave,onReset,busy,demo,role,preferences,onPreferences}:{masters:Master[];rows:Applicant[];onSave:(next:Master,rename?:Rename)=>Promise<boolean>;onReset:()=>void;busy:boolean;demo:boolean;role:StaffDepartment;preferences:Preferences;onPreferences:(next:Preferences)=>void}){
 const editable=role==='admin';
 const [category,setCategory]=useState<Category>('display'),[department,setDepartment]=useState<Department>(role==='welfare'?'welfare':'therapy'),[error,setError]=useState(''),[newMedia,setNewMedia]=useState(''),[newJob,setNewJob]=useState(''),[confirm,setConfirm]=useState<{master:Master;rename?:Rename;message:string}|null>(null);
 const dialog=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 const master=masters.find(m=>m.department===department);
 const locked=busy||!!confirm;
 useEffect(()=>{if(!confirm)return;previousFocus.current=document.activeElement as HTMLElement;const before=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>{document.body.style.overflow=before;previousFocus.current?.focus();};},[!!confirm]);
 function propose(next:Master,message:string,rename?:Rename){if(!editable||locked)return;try{validateMaster(next);setError('');setConfirm({master:next,message,rename});}catch(e){setError((e as Error).message);}}
 function move(kind:'media'|'job',index:number,diff:number){if(!master||!editable||locked)return;const next=structuredClone(master);const list=kind==='media'?next.media:next.jobs;const other=index+diff;if(other<0||other>=list.length)return;[list[index],list[other]]=[list[other],list[index]];void onSave(next);}
 const count=(kind:'media'|'job',name:string)=>rows.filter(r=>r.department===department&&(kind==='media'?mediaOf(r):jobOf(r))===name).length;
 function remove(kind:'media'|'job',name:string){if(!master)return;const n=count(kind,name);if(n){setError(`${n}名の応募者が使っています。先に応募者の項目を変更してください。保管中の応募者も含みます。`);return;}const next=structuredClone(master);if(kind==='media')next.media=next.media.filter(m=>m!==name);else next.jobs=next.jobs.filter(j=>j.name!==name);propose(next,`「${name}」を選択肢から削除します。`);}
 function editName(kind:'media'|'job',name:string,value:string){if(!master)return;const next=structuredClone(master);if(kind==='media')next.media=next.media.map(m=>m===name?value:m);else next.jobs=next.jobs.map(j=>j.name===name?{...j,name:value}:j);propose(next,`「${name}」を「${value}」へ変更し、同部門の応募者${count(kind,name)}名にも反映します。`,{kind,oldName:name,newName:value});}
 const editor=(kind:'media'|'job',name:string,index:number)=><form className="master-row" key={`${department}:${kind}:${name}`} onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('name')||'').trim();if(value!==name)editName(kind,name,value);}}><div className="master-item-heading"><span className="master-order" aria-label={`表示順 ${index+1}`}>{index+1}</span><label>{kind==='media'?'媒体名':'職種名'}<input name="name" defaultValue={name} required maxLength={200} disabled={locked||!editable} aria-label={`${name}の名称`}/></label></div><span className="master-usage">使用 {count(kind,name)}名</span>{editable&&<div className="actions"><button disabled={locked}>名称を変更する</button>{kind==='job'&&<button type="button" className={master!.jobs[index].open?'status-toggle open':'status-toggle'} aria-pressed={master!.jobs[index].open} disabled={locked} onClick={()=>{const next=structuredClone(master!);next.jobs[index].open=!next.jobs[index].open;propose(next,`「${name}」を${next.jobs[index].open?'募集中':'募集停止'}へ変更します。`);}}>{master!.jobs[index].open?'募集中':'募集停止中'}</button>}<div className="reorder-actions"><button type="button" disabled={locked||index===0} onClick={()=>move(kind,index,-1)} aria-label={`${name}を上へ`}>上へ</button><button type="button" disabled={locked||index===(kind==='media'?master!.media:master!.jobs).length-1} onClick={()=>move(kind,index,1)} aria-label={`${name}を下へ`}>下へ</button></div><button className="quiet-danger" type="button" disabled={locked} onClick={()=>remove(kind,name)} aria-label={`${name}を削除`}>削除</button></div>}{!editable&&kind==='job'&&<span className="badge neutral">{master!.jobs[index].open?'募集中':'募集停止中'}</span>}</form>;
 const categories:{id:Category;title:string;description:string}[]=[{id:'display',title:'表示',description:'使いやすい画面に'},{id:'media',title:'応募媒体',description:'応募の入口を管理'},{id:'jobs',title:'職種・募集状況',description:'募集する仕事を管理'},{id:'access',title:'利用権限',description:'所属と操作範囲'}];
 return <div className="settings-layout"><nav className="settings-nav" aria-label="設定カテゴリ">{categories.map(c=><button key={c.id} disabled={locked} aria-current={category===c.id?'page':undefined} className={category===c.id?'active':''} onClick={()=>{setCategory(c.id);setError('');}}><strong>{c.title}</strong><span>{c.description}</span></button>)}</nav><div className="settings-content">
 {category==='display'&&<section className="panel"><h2>いつもの画面を、自分に合わせる</h2><p className="muted">このブラウザの、選択したログイン部門に保存します。</p><div className="settings-field"><div><h3>ログイン後に開く画面</h3><p className="muted">よく使う画面から仕事を始められます。</p></div><label>最初に開く画面<select value={preferences.startView} onChange={e=>onPreferences({...preferences,startView:e.target.value as Preferences['startView']})}><option value="dashboard">採用ホーム</option><option value="board">応募者ボード</option><option value="calendar">採用カレンダー</option><option value="list">応募者一覧</option></select></label></div><div className="settings-field"><div><h3>表示のゆとり</h3><p className="muted">文字とボタンの押しやすさは保ち、一覧の余白を調整します。</p></div><div className="segmented" role="group" aria-label="表示のゆとり"><button aria-pressed={preferences.density==='comfortable'} onClick={()=>onPreferences({...preferences,density:'comfortable'})}>ゆったり</button><button aria-pressed={preferences.density==='compact'} onClick={()=>onPreferences({...preferences,density:'compact'})}>コンパクト</button></div></div><p className="settings-save-note" role="status">表示設定は変更すると保存されます。</p></section>}
 {(category==='media'||category==='jobs')&&<><section className="settings-scope"><div><h2>{category==='media'?'応募媒体':'職種・募集状況'}</h2><p className="muted">{editable?'応募者の入力候補と、一覧での表示順を管理します。':'所属部門の設定を確認できます。変更は全社管理者へ依頼してください。'}</p></div><label>設定する部門<select disabled={locked||!editable} value={department} onChange={e=>{setDepartment(e.target.value as Department);setError('');setNewMedia('');setNewJob('');}}>{(editable||role==='therapy')&&<option value="therapy">療術部門</option>}{(editable||role==='welfare')&&<option value="welfare">GH部門</option>}</select></label></section>{error&&<p className="banner error" role="alert">{error}</p>}{!master?<section className="empty">設定を取得できませんでした。一覧を更新して再度開いてください。</section>:<section className="panel master-panel"><p className="muted">{category==='media'?`${master.media.length}媒体。上から順に入力候補へ表示します。`:`${master.jobs.filter(j=>j.open).length}職種が募集中。募集状況は社内の一覧に反映します。`}</p>{category==='media'?master.media.map((name,i)=>editor('media',name,i)):master.jobs.map((job,i)=>editor('job',job.name,i))}{editable&&<form className="master-add" onSubmit={e=>{e.preventDefault();if(category==='media')propose({...master,media:[...master.media,newMedia.trim()]},`媒体「${newMedia.trim()}」を追加します。`);else propose({...master,jobs:[...master.jobs,{name:newJob.trim(),open:true}]},`職種「${newJob.trim()}」を募集中として追加します。`);}}><label>{category==='media'?'追加する媒体':'追加する職種'}<input required maxLength={200} disabled={locked} value={category==='media'?newMedia:newJob} onChange={e=>category==='media'?setNewMedia(e.target.value):setNewJob(e.target.value)}/></label><button className="primary" disabled={locked}>{category==='media'?'媒体を追加する':'職種を追加する'}</button></form>}<p className="muted settings-footnote">既存の応募者が使っている項目は削除できません。外部の求人サイトへの投稿は行いません。</p></section>}</>}
 {category==='access'&&<><section className="panel"><h2>所属と利用できる機能</h2><dl className="settings-access"><dt>ログイン部門</dt><dd>{role==='admin'?'全社管理者':role==='therapy'?'療術部門':'GH部門'}</dd><dt>応募者・LINE履歴</dt><dd>{editable?'療術・GHの両部門':'所属部門のみ'}</dd><dt>媒体・職種の変更</dt><dd>{editable?'変更できます':'全社管理者が変更します'}</dd><dt>利用環境</dt><dd>{demo?'サンプルデータの確認版':'スタッフアカウントで接続中'}</dd></dl><p className="muted">スタッフの追加・所属変更は管理者が行います。</p></section>{demo&&editable&&<section className="panel"><h2>サンプルデータを初期状態へ戻す</h2><p className="muted">架空の応募者と媒体・職種の設定を戻します。表示設定はそのまま残ります。</p><button className="quiet-danger" disabled={busy} onClick={onReset}>デモデータをリセットする</button></section>}</>}
 </div>{confirm&&<div className="backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setConfirm(null);}}><div className="dialog settings-confirm" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="settings-confirm-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)setConfirm(null);if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')??[]),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section role="region" aria-label="設定変更の確認"><h2 id="settings-confirm-title">変更内容を確認する</h2><p>{confirm.message}</p>{error&&<p className="banner error" role="alert">{error}</p>}<p className="muted">保存すると、この部門の設定へ反映します。</p><div className="dialog-foot"><button disabled={busy} onClick={()=>setConfirm(null)}>変更を取り消す</button><button disabled={busy} className="primary" onClick={()=>{void onSave(confirm.master,confirm.rename).then(saved=>{if(saved){setConfirm(null);setNewMedia('');setNewJob('');}else setError('保存できませんでした。接続状態と画面上部のエラーを確認して再試行してください。');});}}>{busy?'保存しています…':'設定を保存する'}</button></div></section></div></div>}</div>;
}
